// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/url"

	"github.com/google/uuid"
)

// Ref: #/components/schemas/Dish
type Dish struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Image url.URL   `json:"image"`
	Price float64   `json:"price"`
}

// GetID returns the value of ID.
func (s *Dish) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Dish) GetName() string {
	return s.Name
}

// GetImage returns the value of Image.
func (s *Dish) GetImage() url.URL {
	return s.Image
}

// GetPrice returns the value of Price.
func (s *Dish) GetPrice() float64 {
	return s.Price
}

// SetID sets the value of ID.
func (s *Dish) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Dish) SetName(val string) {
	s.Name = val
}

// SetImage sets the value of Image.
func (s *Dish) SetImage(val url.URL) {
	s.Image = val
}

// SetPrice sets the value of Price.
func (s *Dish) SetPrice(val float64) {
	s.Price = val
}

func (*Dish) retrieveDishByIDRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	Code    float64 `json:"code"`
	Message string  `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() float64 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val float64) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) retrieveListOfRestaurantsRes() {}

// Ref: #/components/schemas/Menu
type Menu struct {
	ID         OptUUID `json:"id"`
	Restaurant OptUUID `json:"restaurant"`
	Image      OptURI  `json:"image"`
	Dishes     []Dish  `json:"dishes"`
}

// GetID returns the value of ID.
func (s *Menu) GetID() OptUUID {
	return s.ID
}

// GetRestaurant returns the value of Restaurant.
func (s *Menu) GetRestaurant() OptUUID {
	return s.Restaurant
}

// GetImage returns the value of Image.
func (s *Menu) GetImage() OptURI {
	return s.Image
}

// GetDishes returns the value of Dishes.
func (s *Menu) GetDishes() []Dish {
	return s.Dishes
}

// SetID sets the value of ID.
func (s *Menu) SetID(val OptUUID) {
	s.ID = val
}

// SetRestaurant sets the value of Restaurant.
func (s *Menu) SetRestaurant(val OptUUID) {
	s.Restaurant = val
}

// SetImage sets the value of Image.
func (s *Menu) SetImage(val OptURI) {
	s.Image = val
}

// SetDishes sets the value of Dishes.
func (s *Menu) SetDishes(val []Dish) {
	s.Dishes = val
}

func (*Menu) retrieveMenuByIDRes() {}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type RetrieveDishByIDInternalServerError Error

func (*RetrieveDishByIDInternalServerError) retrieveDishByIDRes() {}

type RetrieveDishByIDNotFound Error

func (*RetrieveDishByIDNotFound) retrieveDishByIDRes() {}

type RetrieveDishesByMenuIdInternalServerError Error

func (*RetrieveDishesByMenuIdInternalServerError) retrieveDishesByMenuIdRes() {}

type RetrieveDishesByMenuIdNotFound Error

func (*RetrieveDishesByMenuIdNotFound) retrieveDishesByMenuIdRes() {}

type RetrieveDishesByMenuIdOKApplicationJSON []Dish

func (*RetrieveDishesByMenuIdOKApplicationJSON) retrieveDishesByMenuIdRes() {}

type RetrieveListOfRestaurantsOKApplicationJSON []uuid.UUID

func (*RetrieveListOfRestaurantsOKApplicationJSON) retrieveListOfRestaurantsRes() {}

type RetrieveMenuByIDInternalServerError Error

func (*RetrieveMenuByIDInternalServerError) retrieveMenuByIDRes() {}

type RetrieveMenuByIDNotFound Error

func (*RetrieveMenuByIDNotFound) retrieveMenuByIDRes() {}

type RetrieveMenusByRestaurantInternalServerError Error

func (*RetrieveMenusByRestaurantInternalServerError) retrieveMenusByRestaurantRes() {}

type RetrieveMenusByRestaurantNotFound Error

func (*RetrieveMenusByRestaurantNotFound) retrieveMenusByRestaurantRes() {}

type RetrieveMenusByRestaurantOKApplicationJSON []Menu

func (*RetrieveMenusByRestaurantOKApplicationJSON) retrieveMenusByRestaurantRes() {}

type ValidateRestaurantDishesBadRequest Error

func (*ValidateRestaurantDishesBadRequest) validateRestaurantDishesRes() {}

type ValidateRestaurantDishesInternalServerError Error

func (*ValidateRestaurantDishesInternalServerError) validateRestaurantDishesRes() {}

type ValidateRestaurantDishesNotFound Error

func (*ValidateRestaurantDishesNotFound) validateRestaurantDishesRes() {}

// ValidateRestaurantDishesOK is response for ValidateRestaurantDishes operation.
type ValidateRestaurantDishesOK struct{}

func (*ValidateRestaurantDishesOK) validateRestaurantDishesRes() {}

// Ref: #/components/schemas/ValidationList
type ValidationList struct {
	Restaurant uuid.UUID   `json:"restaurant"`
	Dishes     []uuid.UUID `json:"dishes"`
}

// GetRestaurant returns the value of Restaurant.
func (s *ValidationList) GetRestaurant() uuid.UUID {
	return s.Restaurant
}

// GetDishes returns the value of Dishes.
func (s *ValidationList) GetDishes() []uuid.UUID {
	return s.Dishes
}

// SetRestaurant sets the value of Restaurant.
func (s *ValidationList) SetRestaurant(val uuid.UUID) {
	s.Restaurant = val
}

// SetDishes sets the value of Dishes.
func (s *ValidationList) SetDishes(val []uuid.UUID) {
	s.Dishes = val
}
