// Code generated by ogen, DO NOT EDIT.
package api

type RetrieveDishByIDRes interface {
	retrieveDishByIDRes()
}

type RetrieveListOfRestaurantsRes interface {
	retrieveListOfRestaurantsRes()
}

type RetrieveMenuByIDRes interface {
	retrieveMenuByIDRes()
}

type RetrieveMenusByRestaurantRes interface {
	retrieveMenusByRestaurantRes()
}

type ValidateRestaurantDishesRes interface {
	validateRestaurantDishesRes()
}
