// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// RetrieveDishByID implements RetrieveDishByID operation.
//
// Retrieve dish by its ID.
//
// GET /dish/{id}
func (UnimplementedHandler) RetrieveDishByID(ctx context.Context, params RetrieveDishByIDParams) (r RetrieveDishByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RetrieveListOfRestaurants implements RetrieveListOfRestaurants operation.
//
// Retrieve list of IDs of restaurants.
//
// GET /restaurant
func (UnimplementedHandler) RetrieveListOfRestaurants(ctx context.Context) (r RetrieveListOfRestaurantsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RetrieveMenuByID implements RetrieveMenuByID operation.
//
// Retrieve menu data by its ID.
//
// GET /menu/{id}
func (UnimplementedHandler) RetrieveMenuByID(ctx context.Context, params RetrieveMenuByIDParams) (r RetrieveMenuByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RetrieveMenusByRestaurant implements RetrieveMenusByRestaurant operation.
//
// Retrieve menu data by its restaurant's ID.
//
// GET /menu/restaurant/{id}
func (UnimplementedHandler) RetrieveMenusByRestaurant(ctx context.Context, params RetrieveMenusByRestaurantParams) (r RetrieveMenusByRestaurantRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ValidateRestaurantDishes implements ValidateRestaurantDishes operation.
//
// Validates restaurant ownership for dishes.
//
// POST /restaurant/validate-dishes
func (UnimplementedHandler) ValidateRestaurantDishes(ctx context.Context, req *ValidationList) (r ValidateRestaurantDishesRes, _ error) {
	return r, ht.ErrNotImplemented
}
