// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package data

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDish = `-- name: DeleteDish :exec
UPDATE dishes
SET is_deleted = TRUE
WHERE id = $1 AND is_deleted = FALSE
`

func (q *Queries) DeleteDish(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDish, id)
	return err
}

const insertDish = `-- name: InsertDish :exec
INSERT INTO dishes(id, name, image, price)
VALUES ($1, $2, $3, $4)
`

type InsertDishParams struct {
	ID    pgtype.UUID
	Name  string
	Image string
	Price float64
}

func (q *Queries) InsertDish(ctx context.Context, arg InsertDishParams) error {
	_, err := q.db.Exec(ctx, insertDish,
		arg.ID,
		arg.Name,
		arg.Image,
		arg.Price,
	)
	return err
}

const retrieveDishByID = `-- name: RetrieveDishByID :one
SELECT id, name, image, price, is_deleted FROM dishes WHERE id = $1 AND is_deleted = FALSE
`

func (q *Queries) RetrieveDishByID(ctx context.Context, id pgtype.UUID) (Dish, error) {
	row := q.db.QueryRow(ctx, retrieveDishByID, id)
	var i Dish
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.Price,
		&i.IsDeleted,
	)
	return i, err
}

const retrieveDishByMenu = `-- name: RetrieveDishByMenu :many
SELECT d.id, d.name, d.image, d.price, d.is_deleted FROM dishes d
JOIN menu_dish md ON dm.dish = d.id
JOIN menus m ON m.id = md.menu
WHERE m.id = $1 AND m.is_deleted = FALSE AND d.is_deleted = FALSE
`

func (q *Queries) RetrieveDishByMenu(ctx context.Context, id pgtype.UUID) ([]Dish, error) {
	rows, err := q.db.Query(ctx, retrieveDishByMenu, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dish
	for rows.Next() {
		var i Dish
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.Price,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrieveDishesByRestaurant = `-- name: RetrieveDishesByRestaurant :many
SELECT d.id, d.name, d.image, d.price, d.is_deleted FROM dishes d
JOIN menu_dish md ON dm.dish = d.id
JOIN menus m ON m.id = md.menu
WHERE m.restaurant = $1 AND m.is_deleted = FALSE
`

func (q *Queries) RetrieveDishesByRestaurant(ctx context.Context, restaurant pgtype.UUID) ([]Dish, error) {
	rows, err := q.db.Query(ctx, retrieveDishesByRestaurant, restaurant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dish
	for rows.Next() {
		var i Dish
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.Price,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrieveDishesIdsByMenu = `-- name: RetrieveDishesIdsByMenu :many
SELECT dish FROM menu_dish
WHERE menu = $1
`

func (q *Queries) RetrieveDishesIdsByMenu(ctx context.Context, menu pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, retrieveDishesIdsByMenu, menu)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var dish pgtype.UUID
		if err := rows.Scan(&dish); err != nil {
			return nil, err
		}
		items = append(items, dish)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrieveMenuByID = `-- name: RetrieveMenuByID :one
SELECT id, name, image, restaurant, is_deleted FROM menus WHERE id = $1 AND is_deleted = FALSE
`

func (q *Queries) RetrieveMenuByID(ctx context.Context, id pgtype.UUID) (Menu, error) {
	row := q.db.QueryRow(ctx, retrieveMenuByID, id)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.Restaurant,
		&i.IsDeleted,
	)
	return i, err
}

const retrieveMenusByRestaurant = `-- name: RetrieveMenusByRestaurant :many
SELECT id, name, image, restaurant, is_deleted FROM menus WHERE restaurant = $1 AND is_deleted = FALSE
`

func (q *Queries) RetrieveMenusByRestaurant(ctx context.Context, restaurant pgtype.UUID) ([]Menu, error) {
	rows, err := q.db.Query(ctx, retrieveMenusByRestaurant, restaurant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Menu
	for rows.Next() {
		var i Menu
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.Restaurant,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDish = `-- name: UpdateDish :exec
UPDATE dishes
SET name = $2, image = $3, price = $4
WHERE id = $1 AND is_deleted = FALSE
`

type UpdateDishParams struct {
	ID    pgtype.UUID
	Name  string
	Image string
	Price float64
}

func (q *Queries) UpdateDish(ctx context.Context, arg UpdateDishParams) error {
	_, err := q.db.Exec(ctx, updateDish,
		arg.ID,
		arg.Name,
		arg.Image,
		arg.Price,
	)
	return err
}
