// Code generated by ogen, DO NOT EDIT.
package api

type LogInRes interface {
	logInRes()
}

type LogoutFromSessionRes interface {
	logoutFromSessionRes()
}

type RefreshAccessTokenRes interface {
	refreshAccessTokenRes()
}

type RefreshPairRes interface {
	refreshPairRes()
}
