// Code generated by ogen, DO NOT EDIT.

package api

// Ref: #/components/schemas/AccessToken
type AccessToken struct {
	AccessToken string `json:"accessToken"`
}

// GetAccessToken returns the value of AccessToken.
func (s *AccessToken) GetAccessToken() string {
	return s.AccessToken
}

// SetAccessToken sets the value of AccessToken.
func (s *AccessToken) SetAccessToken(val string) {
	s.AccessToken = val
}

func (*AccessToken) refreshAccessTokenRes() {}

// Ref: #/components/schemas/Credentials
type Credentials struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

// GetPhone returns the value of Phone.
func (s *Credentials) GetPhone() string {
	return s.Phone
}

// GetPassword returns the value of Password.
func (s *Credentials) GetPassword() string {
	return s.Password
}

// SetPhone sets the value of Phone.
func (s *Credentials) SetPhone(val string) {
	s.Phone = val
}

// SetPassword sets the value of Password.
func (s *Credentials) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/Error
type Error struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

type LogInBadRequest Error

func (*LogInBadRequest) logInRes() {}

type LogInInternalServerError Error

func (*LogInInternalServerError) logInRes() {}

type LogoutFromSessionBadRequest Error

func (*LogoutFromSessionBadRequest) logoutFromSessionRes() {}

type LogoutFromSessionInternalServerError Error

func (*LogoutFromSessionInternalServerError) logoutFromSessionRes() {}

// LogoutFromSessionOK is response for LogoutFromSession operation.
type LogoutFromSessionOK struct{}

func (*LogoutFromSessionOK) logoutFromSessionRes() {}

type RefreshAccessTokenBadRequest Error

func (*RefreshAccessTokenBadRequest) refreshAccessTokenRes() {}

type RefreshAccessTokenInternalServerError Error

func (*RefreshAccessTokenInternalServerError) refreshAccessTokenRes() {}

type RefreshAuth struct {
	APIKey string
}

// GetAPIKey returns the value of APIKey.
func (s *RefreshAuth) GetAPIKey() string {
	return s.APIKey
}

// SetAPIKey sets the value of APIKey.
func (s *RefreshAuth) SetAPIKey(val string) {
	s.APIKey = val
}

type RefreshPairBadRequest Error

func (*RefreshPairBadRequest) refreshPairRes() {}

type RefreshPairInternalServerError Error

func (*RefreshPairInternalServerError) refreshPairRes() {}

// Ref: #/components/schemas/TokenPair
type TokenPair struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

// GetAccessToken returns the value of AccessToken.
func (s *TokenPair) GetAccessToken() string {
	return s.AccessToken
}

// GetRefreshToken returns the value of RefreshToken.
func (s *TokenPair) GetRefreshToken() string {
	return s.RefreshToken
}

// SetAccessToken sets the value of AccessToken.
func (s *TokenPair) SetAccessToken(val string) {
	s.AccessToken = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *TokenPair) SetRefreshToken(val string) {
	s.RefreshToken = val
}

func (*TokenPair) logInRes()       {}
func (*TokenPair) refreshPairRes() {}
