// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// LogIn implements LogIn operation.
//
// Log into account and create a session.
//
// POST /login
func (UnimplementedHandler) LogIn(ctx context.Context, req *Credentials) (r LogInRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LogoutFromSession implements LogoutFromSession operation.
//
// Log out from the account using refresh token.
//
// POST /logout
func (UnimplementedHandler) LogoutFromSession(ctx context.Context) (r LogoutFromSessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RefreshAccessToken implements RefreshAccessToken operation.
//
// Create a new access token using refresh token.
//
// POST /access
func (UnimplementedHandler) RefreshAccessToken(ctx context.Context) (r RefreshAccessTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RefreshPair implements RefreshPair operation.
//
// Refresh pair of tokens using refresh token.
//
// POST /refresh
func (UnimplementedHandler) RefreshPair(ctx context.Context) (r RefreshPairRes, _ error) {
	return r, ht.ErrNotImplemented
}
