// Code generated by ogen, DO NOT EDIT.

package api

// Ref: #/components/schemas/AccessToken
type AccessToken struct {
	AccessToken string `json:"accessToken"`
}

// GetAccessToken returns the value of AccessToken.
func (s *AccessToken) GetAccessToken() string {
	return s.AccessToken
}

// SetAccessToken sets the value of AccessToken.
func (s *AccessToken) SetAccessToken(val string) {
	s.AccessToken = val
}

func (*AccessToken) refreshAccessTokenRes() {}

// Ref: #/components/schemas/Credentials
type Credentials struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

// GetPhone returns the value of Phone.
func (s *Credentials) GetPhone() string {
	return s.Phone
}

// GetPassword returns the value of Password.
func (s *Credentials) GetPassword() string {
	return s.Password
}

// SetPhone sets the value of Phone.
func (s *Credentials) SetPhone(val string) {
	s.Phone = val
}

// SetPassword sets the value of Password.
func (s *Credentials) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/Error
type Error struct {
	Code    OptInt    `json:"code"`
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val OptString) {
	s.Message = val
}

type LogInBadRequest Error

func (*LogInBadRequest) logInRes() {}

type LogInInternalServerError Error

func (*LogInInternalServerError) logInRes() {}

type LogoutFromSessionBadRequest Error

func (*LogoutFromSessionBadRequest) logoutFromSessionRes() {}

type LogoutFromSessionInternalServerError Error

func (*LogoutFromSessionInternalServerError) logoutFromSessionRes() {}

// LogoutFromSessionOK is response for LogoutFromSession operation.
type LogoutFromSessionOK struct{}

func (*LogoutFromSessionOK) logoutFromSessionRes() {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type RefreshAccessTokenBadRequest Error

func (*RefreshAccessTokenBadRequest) refreshAccessTokenRes() {}

type RefreshAccessTokenInternalServerError Error

func (*RefreshAccessTokenInternalServerError) refreshAccessTokenRes() {}

type RefreshAuth struct {
	APIKey string
}

// GetAPIKey returns the value of APIKey.
func (s *RefreshAuth) GetAPIKey() string {
	return s.APIKey
}

// SetAPIKey sets the value of APIKey.
func (s *RefreshAuth) SetAPIKey(val string) {
	s.APIKey = val
}

type RefreshPairBadRequest Error

func (*RefreshPairBadRequest) refreshPairRes() {}

type RefreshPairInternalServerError Error

func (*RefreshPairInternalServerError) refreshPairRes() {}

// Ref: #/components/schemas/TokenPair
type TokenPair struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

// GetAccessToken returns the value of AccessToken.
func (s *TokenPair) GetAccessToken() string {
	return s.AccessToken
}

// GetRefreshToken returns the value of RefreshToken.
func (s *TokenPair) GetRefreshToken() string {
	return s.RefreshToken
}

// SetAccessToken sets the value of AccessToken.
func (s *TokenPair) SetAccessToken(val string) {
	s.AccessToken = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *TokenPair) SetRefreshToken(val string) {
	s.RefreshToken = val
}

func (*TokenPair) logInRes()       {}
func (*TokenPair) refreshPairRes() {}
