// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleRefreshAuth handles refreshAuth security.
	HandleRefreshAuth(ctx context.Context, operationName string, t RefreshAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

func (s *Server) securityRefreshAuth(ctx context.Context, operationName string, req *http.Request) (context.Context, bool, error) {
	var t RefreshAuth
	const parameterName = "refresh_token"
	var value string
	switch cookie, err := req.Cookie(parameterName); {
	case err == nil: // if NO error
		value = cookie.Value
	case errors.Is(err, http.ErrNoCookie):
		return ctx, false, nil
	default:
		return nil, false, errors.Wrap(err, "get cookie value")
	}
	t.APIKey = value
	rctx, err := s.sec.HandleRefreshAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// RefreshAuth provides refreshAuth security value.
	RefreshAuth(ctx context.Context, operationName string) (RefreshAuth, error)
}

func (s *Client) securityRefreshAuth(ctx context.Context, operationName string, req *http.Request) error {
	t, err := s.sec.RefreshAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"RefreshAuth\"")
	}
	req.AddCookie(&http.Cookie{
		Name:  "refresh_token",
		Value: t.APIKey,
	})
	return nil
}
