// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID             pgtype.UUID
	Phone          string
	Password       string
	Name           pgtype.Text
	ProfilePicture pgtype.Text
}
