// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ValidateCredentials implements ValidateCredentials operation.
//
// GET /account/credentials
func (UnimplementedHandler) ValidateCredentials(ctx context.Context, req *AccountCredentials) (r ValidateCredentialsRes, _ error) {
	return r, ht.ErrNotImplemented
}
