version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "./migrations"
    gen:
      go:
        package: "gen"
        out: "gen"
        sql_package: "pgx/v5"
        overrides:
          - db_type: "uuid"
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"
