// Code generated by ogen, DO NOT EDIT.
package api

type CreateAccountRes interface {
	createAccountRes()
}

type GetAccountInfoRes interface {
	getAccountInfoRes()
}

type GetOwnInfoRes interface {
	getOwnInfoRes()
}

type UpdatePasswordRes interface {
	updatePasswordRes()
}
