// Code generated by ogen, DO NOT EDIT.

package api

// Ref: #/components/schemas/AccountCreationInfo
type AccountCreationInfo struct {
	Phone    string    `json:"phone"`
	Password string    `json:"password"`
	Name     OptString `json:"name"`
}

// GetPhone returns the value of Phone.
func (s *AccountCreationInfo) GetPhone() string {
	return s.Phone
}

// GetPassword returns the value of Password.
func (s *AccountCreationInfo) GetPassword() string {
	return s.Password
}

// GetName returns the value of Name.
func (s *AccountCreationInfo) GetName() OptString {
	return s.Name
}

// SetPhone sets the value of Phone.
func (s *AccountCreationInfo) SetPhone(val string) {
	s.Phone = val
}

// SetPassword sets the value of Password.
func (s *AccountCreationInfo) SetPassword(val string) {
	s.Password = val
}

// SetName sets the value of Name.
func (s *AccountCreationInfo) SetName(val OptString) {
	s.Name = val
}

// Ref: #/components/schemas/AccountId
type AccountId struct {
	ID string `json:"id"`
}

// GetID returns the value of ID.
func (s *AccountId) GetID() string {
	return s.ID
}

// SetID sets the value of ID.
func (s *AccountId) SetID(val string) {
	s.ID = val
}

func (*AccountId) createAccountRes() {}

// Ref: #/components/schemas/AccountInfo
type AccountInfo struct {
	ID    string    `json:"id"`
	Phone string    `json:"phone"`
	Name  OptString `json:"name"`
}

// GetID returns the value of ID.
func (s *AccountInfo) GetID() string {
	return s.ID
}

// GetPhone returns the value of Phone.
func (s *AccountInfo) GetPhone() string {
	return s.Phone
}

// GetName returns the value of Name.
func (s *AccountInfo) GetName() OptString {
	return s.Name
}

// SetID sets the value of ID.
func (s *AccountInfo) SetID(val string) {
	s.ID = val
}

// SetPhone sets the value of Phone.
func (s *AccountInfo) SetPhone(val string) {
	s.Phone = val
}

// SetName sets the value of Name.
func (s *AccountInfo) SetName(val OptString) {
	s.Name = val
}

func (*AccountInfo) createAccountRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	Code    OptInt    `json:"code"`
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val OptString) {
	s.Message = val
}

func (*Error) createAccountRes() {}
func (*Error) getOwnInfoRes()    {}

type GetAccountInfoInternalServerError AccountInfo

func (*GetAccountInfoInternalServerError) getAccountInfoRes() {}

type GetAccountInfoNotFound AccountInfo

func (*GetAccountInfoNotFound) getAccountInfoRes() {}

type GetAccountInfoOK AccountInfo

func (*GetAccountInfoOK) getAccountInfoRes() {}

type GetOwnInfoInternalServerError AccountInfo

func (*GetOwnInfoInternalServerError) getOwnInfoRes() {}

type GetOwnInfoNotFound AccountInfo

func (*GetOwnInfoNotFound) getOwnInfoRes() {}

type GetOwnInfoOK AccountInfo

func (*GetOwnInfoOK) getOwnInfoRes() {}

type JWTAuth struct {
	Token string
}

// GetToken returns the value of Token.
func (s *JWTAuth) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *JWTAuth) SetToken(val string) {
	s.Token = val
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PasswordUpdateInfo
type PasswordUpdateInfo struct {
	OldPassword OptString `json:"oldPassword"`
	NewPassword OptString `json:"newPassword"`
}

// GetOldPassword returns the value of OldPassword.
func (s *PasswordUpdateInfo) GetOldPassword() OptString {
	return s.OldPassword
}

// GetNewPassword returns the value of NewPassword.
func (s *PasswordUpdateInfo) GetNewPassword() OptString {
	return s.NewPassword
}

// SetOldPassword sets the value of OldPassword.
func (s *PasswordUpdateInfo) SetOldPassword(val OptString) {
	s.OldPassword = val
}

// SetNewPassword sets the value of NewPassword.
func (s *PasswordUpdateInfo) SetNewPassword(val OptString) {
	s.NewPassword = val
}

type UpdatePasswordBadRequest Error

func (*UpdatePasswordBadRequest) updatePasswordRes() {}

type UpdatePasswordForbidden Error

func (*UpdatePasswordForbidden) updatePasswordRes() {}

type UpdatePasswordInternalServerError AccountInfo

func (*UpdatePasswordInternalServerError) updatePasswordRes() {}

type UpdatePasswordNotFound AccountInfo

func (*UpdatePasswordNotFound) updatePasswordRes() {}

// UpdatePasswordOK is response for UpdatePassword operation.
type UpdatePasswordOK struct{}

func (*UpdatePasswordOK) updatePasswordRes() {}
