// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateAccount implements CreateAccount operation.
//
// Create a new account.
//
// POST /account
func (UnimplementedHandler) CreateAccount(ctx context.Context, req *AccountCreationInfo) (r CreateAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAccountInfo implements GetAccountInfo operation.
//
// Get Account info by its ID.
//
// GET /account/{id}
func (UnimplementedHandler) GetAccountInfo(ctx context.Context, params GetAccountInfoParams) (r GetAccountInfoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOwnInfo implements GetOwnInfo operation.
//
// Retrieve info about own account using jwt token.
//
// GET /account
func (UnimplementedHandler) GetOwnInfo(ctx context.Context) (r GetOwnInfoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePassword implements UpdatePassword operation.
//
// Updates Account's password.
//
// PUT /account/password
func (UnimplementedHandler) UpdatePassword(ctx context.Context, req *PasswordUpdateInfo) (r UpdatePasswordRes, _ error) {
	return r, ht.ErrNotImplemented
}
